# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e4d804856006b736881249a4e55a21aceb98b8f8b3966c91b787b01c03c6f591ebda87d1cf5ade2353bcfde659be62e6eb8fba81d7ae1ef11677bbd1c227b4

test:
  secret_key_base: 8c185f6d959a592c6e3b437d5d3c7a8cdbe7e024bb6a1996d61cf249869f2be86cf2436e7498d9836d7542da98a04a5232e0404f79394ac7bd8eb2e4c928d478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
